
package calc_fin;

import java.text.DecimalFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author papiro
 */
public class TelaDesconto extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
       private final negocioDesc form;
       private final taxaTempo form1;
       private double nominal;
       private double taxa;
       private double tempo;
       private double valorAtual;
       private double desconto;
       
    public TelaDesconto() {
        initComponents();   
        grupoBotoes();
        form = new negocioDesc();
        form1 = new taxaTempo();
        nominal = 0;
        tempo = 0;
        taxa = 0;
        valorAtual = 0;
        desconto = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        boxTaxa = new javax.swing.JComboBox<>();
        boxTempo = new javax.swing.JComboBox<>();
        txtValorAtual = new javax.swing.JTextField();
        txtTempo = new javax.swing.JTextField();
        txtTaxa = new javax.swing.JTextField();
        txtNominal = new javax.swing.JTextField();
        checkRac = new javax.swing.JRadioButton();
        checkCom = new javax.swing.JRadioButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuInicial = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jInternalFrame1.setBackground(new java.awt.Color(77, 91, 244));
        jInternalFrame1.setForeground(new java.awt.Color(80, 97, 234));
        jInternalFrame1.setVisible(true);

        jLabel1.setText("Desconto:");

        jLabel3.setText("Nominal(N): ");

        jLabel4.setText("Taxa(i): ");

        jLabel5.setText("Tempo(t): ");

        boxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simples", "Composto" }));

        jLabel2.setText("Valor após desconto: ");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        boxTaxa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Mês", "Ano" }));

        boxTempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Mês", "Ano" }));

        checkRac.setText("Racional");
        checkRac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRacActionPerformed(evt);
            }
        });

        checkCom.setText("Comercial");

        menuInicial.setText("Home");
        menuInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicialMouseClicked(evt);
            }
        });
        menuInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicialActionPerformed(evt);
            }
        });
        jMenuBar2.add(menuInicial);

        jInternalFrame1.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnCalcular)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(checkRac)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNominal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtValorAtual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtTempo)
                            .addComponent(txtTaxa))
                        .addGap(39, 39, 39)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkCom)
                            .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRac)
                    .addComponent(checkCom))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(boxTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicialActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuInicialActionPerformed

    private void menuInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicialMouseClicked
        // TODO add your handling code here:
        Inicial form2 = new Inicial();
        form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuInicialMouseClicked

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        nominal = Double.parseDouble(txtNominal.getText());
        taxa = (Double.parseDouble(txtTaxa.getText()))/100;
        //System.out.println("Nominal: "+nominal+"Taxa: "+taxa);
   
        if(checkRac.isSelected() && boxTipo.getSelectedItem().toString().equals("Simples")){
            if(txtTempo.getText().trim().equals("")== false){
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    String taxaS = boxTaxa.getSelectedItem().toString();
                    String tempo = boxTempo.getSelectedItem().toString();
                    taxa = form1.converterTaxa(taxaS, tempo, taxa);
                }
                tempo = Double.parseDouble(txtTempo.getText());
                valorAtual = form.calcSimplesRac(nominal, taxa, tempo);
                desconto = form.calcDesc(nominal,valorAtual);
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado = decimal.format(valorAtual);
                String vF = decimal.format(desconto);

                System.out.println(valorFormatado+"\n"+vF);
                JOptionPane.showMessageDialog(null,"Desconto de: R$ "+vF+"\nValor final de: R$ "+valorFormatado);
            }else if(txtTempo.getText().trim().equals("") && txtValorAtual.getText().trim().equals("") == false){
                valorAtual = Double.parseDouble(txtValorAtual.getText());
                desconto = form.calcDesc(nominal,valorAtual);
                String taxaS = boxTaxa.getSelectedItem().toString();
                String tempoS = boxTempo.getSelectedItem().toString();
                tempo = form1.calcularTempoSimplesRac(nominal, taxa, valorAtual, tempo , taxaS, tempoS);
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    taxaS = boxTaxa.getSelectedItem().toString();
                    tempoS = boxTempo.getSelectedItem().toString();
                    taxa = (form1.converterTaxa(taxaS, tempoS, taxa))/100;
                }
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado = decimal.format(valorAtual);
                String vF = decimal.format(desconto);

                System.out.println(valorFormatado+"\n"+vF);
                String temp = decimal.format(tempo);
                JOptionPane.showMessageDialog(null,"Desconto de: R$ "+vF+"\nValor final de: R$ "+valorFormatado+"\nCom o tempo de: "+temp);
            }

        }
        
        else if (checkRac.isSelected() && boxTipo.getSelectedItem().toString().equals("Composto")){
               if(txtTempo.getText().trim().equals("")== false){
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    String taxaS = boxTaxa.getSelectedItem().toString();
                    String tempo = boxTempo.getSelectedItem().toString();
                    taxa = form1.converterTaxa(taxaS, tempo, taxa);                    
                }
                tempo = Double.parseDouble(txtTempo.getText());
                valorAtual = form.calcCompRac(nominal, taxa, tempo);
                desconto = form.calcDesc(nominal,valorAtual);
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado = decimal.format(valorAtual);
                String vF = decimal.format(desconto);

                System.out.println(valorFormatado+"\n"+vF);
                JOptionPane.showMessageDialog(null,"Desconto de: R$ "+vF+"\nValor final de: R$ "+valorFormatado); 
            }else if(txtTempo.getText().trim().equals("") && txtValorAtual.getText().trim().equals("") == false){
                    valorAtual = Double.parseDouble(txtValorAtual.getText());
                    desconto = form.calcDesc(nominal,valorAtual);
                    String taxaS = boxTaxa.getSelectedItem().toString();
                    String tempoS = boxTempo.getSelectedItem().toString();
                    tempo = form1.calcularTempoCompostoRac(nominal, taxa, valorAtual, tempo , taxaS, tempoS);
                    if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                        taxaS = boxTaxa.getSelectedItem().toString();
                        tempoS = boxTempo.getSelectedItem().toString();
                        taxa = form1.converterTaxa(taxaS, tempoS, taxa);
                    }
                    DecimalFormat decimal = new DecimalFormat("0.00");
                    String valorFormatado = decimal.format(valorAtual);
                    String vF = decimal.format(desconto);

                    System.out.println(valorFormatado+"\n"+vF);
                    String temp = decimal.format(tempo);
                    JOptionPane.showMessageDialog(null,"Desconto de: R$ "+vF+"\nValor final de: R$ "+valorFormatado+"\nCom o tempo de: "+temp);            
                }
        }
        
        else if(checkCom.isSelected() && boxTipo.getSelectedItem().toString().equals("Simples")){
             if(txtTempo.getText().trim().equals("")== false){
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    String taxaS = boxTaxa.getSelectedItem().toString();
                    String tempo = boxTempo.getSelectedItem().toString();
                    taxa = form1.converterTaxa(taxaS, tempo, taxa);
                }
                tempo = Double.parseDouble(txtTempo.getText());
                valorAtual = form.calcSimplesBan(nominal, taxa, tempo);
                desconto = form.calcDesc(nominal,valorAtual);
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado1 = decimal.format(valorAtual);
                String vF1 = decimal.format(desconto);

                System.out.println(valorFormatado1+"\n"+vF1);
                JOptionPane.showMessageDialog(null,"Desconto de: R$ "+vF1+"\nValor final de: R$ "+valorFormatado1);
            }else if(txtTempo.getText().trim().equals("") && txtValorAtual.getText().trim().equals("") == false){
                valorAtual = Double.parseDouble(txtValorAtual.getText());
                desconto = form.calcDesc(nominal,valorAtual);
                String taxaS = boxTaxa.getSelectedItem().toString();
                String tempoS = boxTempo.getSelectedItem().toString();
                tempo = form1.calcularTempoSimplesBan(nominal, taxa, desconto, tempo , taxaS, tempoS);
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    taxaS = boxTaxa.getSelectedItem().toString();
                    tempoS = boxTempo.getSelectedItem().toString();
                    taxa = form1.converterTaxa(taxaS, tempoS, taxa);
                }
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado1 = decimal.format(valorAtual);
                String vF1 = decimal.format(desconto);

                System.out.println(valorFormatado1+"\n"+vF1);
                String temp = decimal.format(tempo);
                JOptionPane.showMessageDialog(null,"Desconto de: R$ "+vF1+"\nValor final de: R$ "+valorFormatado1+"\nCom o tempo de: "+temp);
            }
        }else if(checkCom.isSelected() && boxTipo.getSelectedItem().toString().equals("Composto")){
            if(txtTempo.getText().trim().equals("")== false){
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    String taxaS = boxTaxa.getSelectedItem().toString();
                    String tempo = boxTempo.getSelectedItem().toString();
                    taxa = form1.converterTaxa(taxaS, tempo, taxa);
                }
                tempo = Double.parseDouble(txtTempo.getText());
                valorAtual = form.calcCompBan(nominal, taxa, tempo);
                desconto = form.calcDesc(nominal,valorAtual);
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado1 = decimal.format(valorAtual);
                String vF1 = decimal.format(desconto);

                System.out.println(valorFormatado1+"\n"+vF1);
                JOptionPane.showMessageDialog(null,"Desconto de: R$ "+vF1+"\nValor final de: R$ "+valorFormatado1);
            }else if(txtTempo.getText().trim().equals("") && txtValorAtual.getText().trim().equals("") == false){
                valorAtual = Double.parseDouble(txtValorAtual.getText());
                desconto = form.calcDesc(nominal,valorAtual);
                String taxaS = boxTaxa.getSelectedItem().toString();
                String tempoS = boxTempo.getSelectedItem().toString();
                tempo = form1.calcularTempoCompostoBan(nominal, taxa, valorAtual, tempo , taxaS, tempoS);
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    taxaS = boxTaxa.getSelectedItem().toString();
                    tempoS = boxTempo.getSelectedItem().toString();
                    taxa = form1.converterTaxa(taxaS, tempoS, taxa);
                }
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado1 = decimal.format(valorAtual);
                String vF1 = decimal.format(desconto);

                System.out.println(valorFormatado1+"\n"+vF1);
                String temp = decimal.format(tempo);
                JOptionPane.showMessageDialog(null,"Desconto de: R$ "+vF1+"\nValor final de: R$ "+valorFormatado1+"\nCom o tempo de: "+temp);
            }
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void checkRacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkRacActionPerformed

    private void grupoBotoes(){
        ButtonGroup bG = new ButtonGroup();
        bG.add(checkCom);
        bG.add(checkRac);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDesconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDesconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDesconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDesconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDesconto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTaxa;
    private javax.swing.JComboBox<String> boxTempo;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JRadioButton checkCom;
    private javax.swing.JRadioButton checkRac;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuInicial;
    private javax.swing.JTextField txtNominal;
    private javax.swing.JTextField txtTaxa;
    private javax.swing.JTextField txtTempo;
    private javax.swing.JTextField txtValorAtual;
    // End of variables declaration//GEN-END:variables
}
