/*
OBS: COLOCANDO ZEROS DEMAIS AO CALCULAR JUROS SIMPLES OU COMPOSTO
OBS: PROBLEMAS AO CALCULAR TEMPO
 */
package calc_fin;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author papiro
 */
public class TelaJuros extends javax.swing.JFrame {

    private final negocioJuros form;
    private final taxaTempo form1;
    private double juros;
    private double montante;
    private double capital;
    private double taxa;
    private double tempo;

    /**
     * Creates new form TelaJuros
     */
    public TelaJuros() {
        initComponents();
        form = new negocioJuros();
        form1 = new taxaTempo();
        juros = 0;
        montante = 0;
        capital = 0;
        taxa = 0;
        tempo = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel16 = new javax.swing.JLabel();
        boxTipo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        boxTaxa = new javax.swing.JComboBox<>();
        boxTempo = new javax.swing.JComboBox<>();
        txtCapital = new javax.swing.JTextField();
        txtTaxa = new javax.swing.JTextField();
        txtTempo = new javax.swing.JTextField();
        txtMontante = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuInicial = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jInternalFrame4.setVisible(true);

        jLabel16.setText("Juros: ");

        boxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simples", "Composto" }));

        jLabel17.setText("Capital(C): ");

        jLabel18.setText("Taxa (i): ");

        jLabel19.setText("Tempo(t): ");

        jLabel20.setText("Montante(M):");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        boxTaxa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Mês", "Ano" }));

        boxTempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Mês", "Ano" }));
        boxTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTempoActionPerformed(evt);
            }
        });

        menuInicial.setText("Home");
        menuInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicialMouseClicked(evt);
            }
        });
        menuInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicialActionPerformed(evt);
            }
        });
        jMenuBar2.add(menuInicial);

        jInternalFrame4.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame4Layout.createSequentialGroup()
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(75, 75, 75)))
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMontante)
                            .addComponent(txtCapital)
                            .addComponent(boxTipo, 0, 115, Short.MAX_VALUE)
                            .addComponent(txtTaxa)
                            .addComponent(txtTempo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxTaxa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxTempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(boxTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(boxTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtMontante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(btnCalcular)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTempoActionPerformed

    private void menuInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicialMouseClicked
        // TODO add your handling code here:
        Inicial form2 = new Inicial();
        form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuInicialMouseClicked

    private void menuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicialActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuInicialActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        capital = Double.parseDouble(txtCapital.getText());
        taxa = Double.parseDouble(txtTaxa.getText())/100;
        
        if(boxTipo.getSelectedItem().toString().equals("Simples")){
            if(txtTempo.getText().trim().equals("")== false){
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    String taxaS = boxTaxa.getSelectedItem().toString();
                    String tempo = boxTempo.getSelectedItem().toString();
                    taxa = form1.converterTaxa(taxaS, tempo, taxa);
                }
                tempo = Double.parseDouble(txtTempo.getText());
                juros = form.calcJurosSimples(capital, taxa, tempo);
                montante = form.calcMontante(capital,juros);
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado = decimal.format(montante);
                String vF = decimal.format(juros);

                System.out.println(valorFormatado+"\n"+vF);
                JOptionPane.showMessageDialog(null,"Juros de: R$ "+vF+"\nMontante de: R$ "+valorFormatado);
            }else if(txtTempo.getText().trim().equals("") && txtMontante.getText().trim().equals("") == false){
                montante = Double.parseDouble(txtMontante.getText());
                String taxaS = boxTaxa.getSelectedItem().toString();
                String tempoS = boxTempo.getSelectedItem().toString();
                tempo = form1.calcularTempoJSimples(capital, taxa, montante, tempo , taxaS, tempoS);
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    taxaS = boxTaxa.getSelectedItem().toString();
                    tempoS = boxTempo.getSelectedItem().toString();
                    taxa = (form1.converterTaxa(taxaS, tempoS, taxa))/100;
                }
                juros = form.calcJurosSimples(capital,taxa,tempo);
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado = decimal.format(montante);
                String vF = decimal.format(juros);

                System.out.println(valorFormatado+"\n"+vF);
                String temp = decimal.format(tempo);
                JOptionPane.showMessageDialog(null,"Juros de: R$ "+vF+"\nMontante de: R$ "+valorFormatado+"\nCom o tempo de: "+temp);
            }
        }
        
        else if(boxTipo.getSelectedItem().toString().equals("Composto")){
            if(txtTempo.getText().trim().equals("")== false){
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    String taxaS = boxTaxa.getSelectedItem().toString();
                    String tempo = boxTempo.getSelectedItem().toString();
                    taxa = form1.converterTaxa(taxaS, tempo, taxa);
                }
                tempo = Double.parseDouble(txtTempo.getText());
                juros = form.calcJurosComposto(capital, taxa, tempo);
                montante = form.calcMontante(capital,juros);
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado = decimal.format(montante);
                String vF = decimal.format(juros);

                System.out.println(valorFormatado+"\n"+vF);
                JOptionPane.showMessageDialog(null,"Juros de: R$ "+vF+"\nMontante de: R$ "+valorFormatado);
            }else if(txtTempo.getText().trim().equals("") && txtMontante.getText().trim().equals("") == false){
                montante = Double.parseDouble(txtMontante.getText());
                String taxaS = boxTaxa.getSelectedItem().toString();
                String tempoS = boxTempo.getSelectedItem().toString();
                tempo = form1.calcularTempoJComposto(capital, taxa, montante, tempo , taxaS, tempoS);
                if(boxTaxa.getSelectedItem().toString().equals(boxTempo.getSelectedItem().toString())==false){
                    taxaS = boxTaxa.getSelectedItem().toString();
                    tempoS = boxTempo.getSelectedItem().toString();
                    taxa = (form1.converterTaxa(taxaS, tempoS, taxa))/100;
                }
                juros = form.calcJurosComposto(capital,taxa,tempo);
                DecimalFormat decimal = new DecimalFormat("0.00");
                String valorFormatado = decimal.format(montante);
                String vF = decimal.format(juros);

                System.out.println(valorFormatado+"\n"+vF);
                String temp = decimal.format(tempo);
                JOptionPane.showMessageDialog(null,"Juros de: R$ "+vF+"\nMontante de: R$ "+valorFormatado+"\nCom o tempo de: "+temp);
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJuros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJuros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJuros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJuros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJuros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTaxa;
    private javax.swing.JComboBox<String> boxTempo;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuInicial;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtMontante;
    private javax.swing.JTextField txtTaxa;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables
}
